import Argo
import Ogra

/// A Schema.org type.
public enum SchemaType: String {
    case AboutPage
    case AcceptAction
    case AccountingService
    case AchieveAction
    case Action
    case ActionStatusType
    case ActivateAction
    case AddAction
    case AdministrativeArea
    case AdultEntertainment
    case AggregateOffer
    case AggregateRating
    case AgreeAction
    case Airline
    case Airport
    case AlignmentObject
    case AllocateAction
    case AmusementPark
    case AnatomicalStructure
    case AnatomicalSystem
    case AnimalShelter
    case Answer
    case ApartmentComplex
    case APIReference
    case AppendAction
    case ApplyAction
    case ApprovedIndication
    case Aquarium
    case ArriveAction
    case Artery
    case ArtGallery
    case Article
    case AskAction
    case AssessAction
    case AssignAction
    case Atlas
    case Attorney
    case Audience
    case Audiobook
    case AudioObject
    case AuthorizeAction
    case AutoBodyShop
    case AutoDealer
    case AutomatedTeller
    case AutomotiveBusiness
    case AutoPartsStore
    case AutoRental
    case AutoRepair
    case AutoWash
    case Bakery
    case BankOrCreditUnion
    case Barcode
    case BarOrPub
    case Beach
    case BeautySalon
    case BedAndBreakfast
    case BefriendAction
    case BikeStore
    case Blog
    case BlogPosting
    case BloodTest
    case BoardingPolicyType
    case BodyOfWater
    case Bone
    case Book
    case BookFormatType
    case BookmarkAction
    case BookSeries
    case BookStore
    case BorrowAction
    case BowlingAlley
    case BrainStructure
    case Brand
    case BreadcrumbList
    case Brewery
    case Bridge
    case BroadcastChannel
    case BroadcastEvent
    case BroadcastService
    case BuddhistTemple
    case BusinessAudience
    case BusinessEntityType
    case BusinessEvent
    case BusinessFunction
    case BusOrCoach
    case BusReservation
    case BusStation
    case BusStop
    case BusTrip
    case BuyAction
    case CableOrSatelliteService
    case CafeOrCoffeeShop
    case Campground
    case Canal
    case CancelAction
    case Car
    case CarUsageType
    case Casino
    case CatholicChurch
    case Cemetery
    case Chapter
    case CheckAction
    case CheckInAction
    case CheckOutAction
    case CheckoutPage
    case ChildCare
    case ChildrensEvent
    case ChooseAction
    case Church
    case City
    case CityHall
    case CivicStructure
    case Class
    case Clip
    case ClothingStore
    case Code
    case Collection
    case CollectionPage
    case CollegeOrUniversity
    case ComedyClub
    case ComedyEvent
    case ComicCoverArt
    case ComicIssue
    case ComicSeries
    case ComicStory
    case Comment
    case CommentAction
    case CommunicateAction
    case ComputerStore
    case ConfirmAction
    case ConsumeAction
    case ContactPage
    case ContactPoint
    case ContactPointOption
    case Continent
    case ControlAction
    case ConvenienceStore
    case CookAction
    case Corporation
    case Country
    case Courthouse
    case CoverArt
    case CreateAction
    case CreativeWork
    case CreativeWorkSeason
    case CreativeWorkSeries
    case CreditCard
    case Crematorium
    case DanceEvent
    case DanceGroup
    case DataCatalog
    case DataDownload
    case DataFeed
    case DataFeedItem
    case Dataset
    case DatedMoneySpecification
    case DayOfWeek
    case DaySpa
    case DDxElement
    case DeactivateAction
    case DefenceEstablishment
    case DeleteAction
    case DeliveryChargeSpecification
    case DeliveryEvent
    case DeliveryMethod
    case Demand
    case Dentist
    case DepartAction
    case DepartmentStore
    case DiagnosticLab
    case DiagnosticProcedure
    case Diet
    case DietarySupplement
    case DisagreeAction
    case DiscoverAction
    case DiscussionForumPosting
    case DislikeAction
    case Distance
    case DonateAction
    case DoseSchedule
    case DownloadAction
    case DrawAction
    case DrinkAction
    case DriveWheelConfigurationValue
    case Drug
    case DrugClass
    case DrugCost
    case DrugCostCategory
    case DrugLegalStatus
    case DrugPregnancyCategory
    case DrugPrescriptionStatus
    case DrugStrength
    case DryCleaningOrLaundry
    case Duration
    case EatAction
    case EducationalAudience
    case EducationalOrganization
    case EducationEvent
    case Electrician
    case ElectronicsStore
    case ElementarySchool
    case EmailMessage
    case Embassy
    case EmergencyService
    case EmployeeRole
    case EmploymentAgency
    case EndorseAction
    case Energy
    case EngineSpecification
    case EntertainmentBusiness
    case EntryPoint
    case Enumeration
    case Episode
    case Event
    case EventReservation
    case EventStatusType
    case EventVenue
    case ExerciseAction
    case ExerciseGym
    case ExercisePlan
    case ExhibitionEvent
    case FastFoodRestaurant
    case Festival
    case FilmAction
    case FinancialService
    case FindAction
    case FireStation
    case Flight
    case FlightReservation
    case Florist
    case FollowAction
    case FoodEstablishment
    case FoodEstablishmentReservation
    case FoodEvent
    case FurnitureStore
    case Game
    case GamePlayMode
    case GameServer
    case GameServerStatus
    case GardenStore
    case GasStation
    case GatedResidenceCommunity
    case GeneralContractor
    case GeoCircle
    case GeoCoordinates
    case GeoShape
    case GiveAction
    case GolfCourse
    case GovernmentBuilding
    case GovernmentOffice
    case GovernmentOrganization
    case GovernmentPermit
    case GovernmentService
    case GroceryStore
    case HairSalon
    case HardwareStore
    case HealthAndBeautyBusiness
    case HealthClub
    case HighSchool
    case HinduTemple
    case HobbyShop
    case HomeAndConstructionBusiness
    case HomeGoodsStore
    case Hospital
    case Hostel
    case Hotel
    case HousePainter
    case HVACBusiness
    case IceCreamShop
    case IgnoreAction
    case ImageGallery
    case ImageObject
    case ImagingTest
    case IndividualProduct
    case InfectiousAgentClass
    case InfectiousDisease
    case InformAction
    case InsertAction
    case InstallAction
    case InsuranceAgency
    case Intangible
    case InteractAction
    case InteractionCounter
    case InternetCafe
    case InviteAction
    case Invoice
    case ItemAvailability
    case ItemList
    case ItemListOrderType
    case ItemPage
    case JewelryStore
    case JobPosting
    case JoinAction
    case Joint
    case LakeBodyOfWater
    case Landform
    case LandmarksOrHistoricalBuildings
    case Language
    case LeaveAction
    case LegalService
    case LegislativeBuilding
    case LendAction
    case Library
    case LifestyleModification
    case Ligament
    case LikeAction
    case LiquorStore
    case ListenAction
    case ListItem
    case LiteraryEvent
    case LiveBlogPosting
    case LocalBusiness
    case LockerDelivery
    case Locksmith
    case LodgingBusiness
    case LodgingReservation
    case LoseAction
    case LymphaticVessel
    case Map
    case MapCategoryType
    case MarryAction
    case Mass
    case MaximumDoseSchedule
    case MediaObject
    case MedicalAudience
    case MedicalCause
    case MedicalClinic
    case MedicalCode
    case MedicalCondition
    case MedicalConditionStage
    case MedicalContraindication
    case MedicalDevice
    case MedicalDevicePurpose
    case MedicalEntity
    case MedicalEnumeration
    case MedicalEvidenceLevel
    case MedicalGuideline
    case MedicalGuidelineContraindication
    case MedicalGuidelineRecommendation
    case MedicalImagingTechnique
    case MedicalIndication
    case MedicalIntangible
    case MedicalObservationalStudy
    case MedicalObservationalStudyDesign
    case MedicalOrganization
    case MedicalProcedure
    case MedicalProcedureType
    case MedicalRiskCalculator
    case MedicalRiskEstimator
    case MedicalRiskFactor
    case MedicalRiskScore
    case MedicalScholarlyArticle
    case MedicalSign
    case MedicalSignOrSymptom
    case MedicalSpecialty
    case MedicalStudy
    case MedicalStudyStatus
    case MedicalSymptom
    case MedicalTest
    case MedicalTestPanel
    case MedicalTherapy
    case MedicalTrial
    case MedicalTrialDesign
    case MedicalWebPage
    case MedicineSystem
    case MensClothingStore
    case MiddleSchool
    case MobileApplication
    case MobilePhoneStore
    case Mosque
    case Motel
    case Motorcycle
    case MotorcycleDealer
    case MotorcycleRepair
    case MotorizedBicycle
    case Mountain
    case MoveAction
    case Movie
    case MovieClip
    case MovieRentalStore
    case MovieSeries
    case MovieTheater
    case MovingCompany
    case Muscle
    case Museum
    case MusicAlbum
    case MusicAlbumProductionType
    case MusicAlbumReleaseType
    case MusicComposition
    case MusicEvent
    case MusicGroup
    case MusicPlaylist
    case MusicRecording
    case MusicRelease
    case MusicReleaseFormatType
    case MusicStore
    case MusicVenue
    case MusicVideoObject
    case NailSalon
    case Nerve
    case NewsArticle
    case Newspaper
    case NGO
    case NightClub
    case Notary
    case NutritionInformation
    case OceanBodyOfWater
    case Offer
    case OfferCatalog
    case OfferItemCondition
    case OfficeEquipmentStore
    case OnDemandEvent
    case OpeningHoursSpecification
    case Optician
    case Order
    case OrderAction
    case OrderItem
    case OrderStatus
    case Organization
    case OrganizationRole
    case OrganizeAction
    case OutletStore
    case OwnershipInfo
    case PaintAction
    case Painting
    case PalliativeProcedure
    case ParcelDelivery
    case ParcelService
    case ParentAudience
    case Park
    case ParkingFacility
    case PathologyTest
    case PawnShop
    case PayAction
    case PaymentChargeSpecification
    case PaymentMethod
    case PaymentStatusType
    case PeopleAudience
    case PerformAction
    case PerformanceRole
    case PerformingArtsTheater
    case PerformingGroup
    case Periodical
    case Permit
    case Person
    case PetStore
    case Pharmacy
    case Photograph
    case PhotographAction
    case PhysicalActivity
    case PhysicalActivityCategory
    case PhysicalExam
    case PhysicalTherapy
    case Physician
    case Place
    case PlaceOfWorship
    case PlanAction
    case PlayAction
    case Playground
    case Plumber
    case PoliceStation
    case Pond
    case PostalAddress
    case PostOffice
    case PrependAction
    case Preschool
    case PreventionIndication
    case PriceSpecification
    case Product
    case ProductModel
    case ProfessionalService
    case ProfilePage
    case ProgramMembership
    case Property
    case PropertyValue
    case PropertyValueSpecification
    case PsychologicalTreatment
    case PublicationEvent
    case PublicationIssue
    case PublicationVolume
    case PublicSwimmingPool
    case QAPage
    case QualitativeValue
    case QuantitativeValue
    case Quantity
    case Question
    case QuoteAction
    case RadiationTherapy
    case RadioChannel
    case RadioClip
    case RadioEpisode
    case RadioSeason
    case RadioSeries
    case RadioStation
    case Rating
    case ReactAction
    case ReadAction
    case RealEstateAgent
    case ReceiveAction
    case Recipe
    case RecommendedDoseSchedule
    case RecyclingCenter
    case RegisterAction
    case RejectAction
    case RentAction
    case RentalCarReservation
    case ReplaceAction
    case ReplyAction
    case Report
    case ReportedDoseSchedule
    case Reservation
    case ReservationPackage
    case ReservationStatusType
    case ReserveAction
    case Reservoir
    case Residence
    case Restaurant
    case ResumeAction
    case ReturnAction
    case Review
    case ReviewAction
    case RiverBodyOfWater
    case Role
    case RoofingContractor
    case RsvpAction
    case RsvpResponseType
    case RVPark
    case SaleEvent
    case ScheduleAction
    case ScholarlyArticle
    case School
    case ScreeningEvent
    case Sculpture
    case SeaBodyOfWater
    case SearchAction
    case SearchResultsPage
    case Season
    case Seat
    case SelfStorage
    case SellAction
    case SendAction
    case Series
    case Service
    case ServiceChannel
    case ShareAction
    case ShoeStore
    case ShoppingCenter
    case SingleFamilyResidence
    case SiteNavigationElement
    case SkiResort
    case SocialEvent
    case SocialMediaPosting
    case SoftwareApplication
    case SoftwareSourceCode
    case SomeProducts
    case Specialty
    case SportingGoodsStore
    case SportsActivityLocation
    case SportsClub
    case SportsEvent
    case SportsOrganization
    case SportsTeam
    case StadiumOrArena
    case State
    case SteeringPositionValue
    case Store
    case StructuredValue
    case SubscribeAction
    case SubwayStation
    case SuperficialAnatomy
    case SuspendAction
    case Synagogue
    case Table
    case TakeAction
    case TattooParlor
    case Taxi
    case TaxiReservation
    case TaxiService
    case TaxiStand
    case TechArticle
    case TelevisionChannel
    case TelevisionStation
    case TennisComplex
    case TheaterEvent
    case TheaterGroup
    case TherapeuticProcedure
    case Thesis
    case Thing
    case Ticket
    case TieAction
    case TipAction
    case TireShop
    case TouristAttraction
    case TouristInformationCenter
    case ToyStore
    case TrackAction
    case TradeAction
    case TrainReservation
    case TrainStation
    case TrainTrip
    case TransferAction
    case TravelAction
    case TravelAgency
    case TreatmentIndication
    case TVClip
    case TVEpisode
    case TVSeason
    case TVSeries
    case TypeAndQuantityNode
    case UnitPriceSpecification
    case UnRegisterAction
    case UpdateAction
    case UseAction
    case UserBlocks
    case UserCheckins
    case UserComments
    case UserDownloads
    case UserInteraction
    case UserLikes
    case UserPageVisits
    case UserPlays
    case UserPlusOnes
    case UserTweets
    case Vehicle
    case Vein
    case Vessel
    case VeterinaryCare
    case VideoGallery
    case VideoGame
    case VideoGameClip
    case VideoGameSeries
    case VideoObject
    case ViewAction
    case VisualArtsEvent
    case VisualArtwork
    case Volcano
    case VoteAction
    case WantAction
    case WarrantyPromise
    case WarrantyScope
    case WatchAction
    case Waterfall
    case WearAction
    case WebApplication
    case WebPage
    case WebPageElement
    case WebSite
    case WholesaleStore
    case WinAction
    case Winery
    case WPAdBlock
    case WPFooter
    case WPHeader
    case WPSideBar
    case WriteAction
    case Zoo
}


// MARK: - Decodable

extension SchemaType: Decodable {}


// MARK: - Encodable

extension SchemaType: Encodable {}
